{
 "title": "Overview",
 "tags": [ "client" ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Event Log Stores",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(stasis_client_persistence_event_log_events_total[$__rate_interval])) by (backend)",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "Key-Value Stores",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(stasis_client_persistence_store_put_operations_total[$__rate_interval])) by (backend)",
     "legendFormat": "Put [{{backend}}]"
    },
    {
     "expr": "sum(rate(stasis_client_persistence_store_get_operations_total[$__rate_interval])) by (backend)",
     "legendFormat": "Get [{{backend}}]"
    },
    {
     "expr": "sum(rate(stasis_client_persistence_store_delete_operations_total[$__rate_interval])) by (backend)",
     "legendFormat": "Delete [{{backend}}]"
    }
   ]
  },
  {
   "title": "OAuth Tokens",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum(stasis_client_oauth_clients_tokens_total) by (endpoint, grant_type)",
     "legendFormat": "{{endpoint}} - {{grant_type}}"
    }
   ]
  },
  {
   "title": "Backup",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Entities",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(stasis_client_operations_backup_entities_handled_total[$__rate_interval])) by (step)",
       "legendFormat": "{{step}}"
      }
     ]
    },
    {
     "title": "Chunks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "rps" } },
     "targets": [
      {
       "expr": "sum(rate(stasis_client_operations_backup_entity_chunks_processed_total[$__rate_interval])) by (step)",
       "legendFormat": "{{step}}"
      }
     ]
    },
    {
     "title": "Entity Bytes",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 19, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(stasis_client_operations_backup_entity_handled_bytes_total[$__rate_interval])) by (step)",
       "legendFormat": "{{step}}"
      }
     ]
    },
    {
     "title": "Total Entity Bytes / Interval",
     "type": "gauge",
     "gridPos": { "h": 11, "w": 5, "x": 19, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(stasis_client_operations_backup_entity_handled_bytes_total[$__range])) by (step)",
       "legendFormat": "{{step}}"
      }
     ]
    },
    {
     "title": "Chunk Bytes",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 19, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(stasis_client_operations_backup_entity_chunk_processed_bytes_total[$__rate_interval])) by (step)",
       "legendFormat": "{{step}}"
      }
     ]
    },
    {
     "title": "Total Chunk Bytes / Interval",
     "type": "gauge",
     "gridPos": { "h": 11, "w": 5, "x": 19, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(stasis_client_operations_backup_entity_chunk_processed_bytes_total[$__range])) by (step)",
       "legendFormat": "{{step}}"
      }
     ]
    },
    {
     "title": "Compressed Chunks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "rps" } },
     "targets": [
      {
       "expr": "sum(rate(stasis_client_operations_backup_entity_chunks_processed_total{step=\"compressed\"}[$__rate_interval])) by (extra)",
       "legendFormat": "{{step}}"
      }
     ]
    },
    {
     "title": "Compressed Chunk Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(stasis_client_operations_backup_entity_chunk_processed_bytes_total{step=\"compressed\"}[$__rate_interval])) by (extra)",
       "legendFormat": "{{extra}}"
      }
     ]
    },
    {
     "title": "Total Compressed Chunk Bytes / Interval",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(stasis_client_operations_backup_entity_chunk_processed_bytes_total{step=\"compressed\"}[$__range])) by (extra)",
       "legendFormat": "{{extra}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Recovery",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Entities",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(stasis_client_operations_recovery_entities_handled_total[$__rate_interval])) by (step)",
       "legendFormat": "{{step}}"
      }
     ]
    },
    {
     "title": "Chunks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "rps" } },
     "targets": [
      {
       "expr": "sum(rate(stasis_client_operations_recovery_entity_chunks_processed_total[$__rate_interval])) by (step)",
       "legendFormat": "{{step}}"
      }
     ]
    },
    {
     "title": "Entity Bytes",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 19, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(stasis_client_operations_recovery_entity_handled_bytes_total[$__rate_interval])) by (step)",
       "legendFormat": "{{step}}"
      }
     ]
    },
    {
     "title": "Total Entity Bytes / Interval",
     "type": "gauge",
     "gridPos": { "h": 11, "w": 5, "x": 19, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(stasis_client_operations_recovery_entity_handled_bytes_total[$__range])) by (step)",
       "legendFormat": "{{step}}"
      }
     ]
    },
    {
     "title": "Chunk Bytes",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 19, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(stasis_client_operations_recovery_entity_chunk_processed_bytes_total[$__rate_interval])) by (step)",
       "legendFormat": "{{step}}"
      }
     ]
    },
    {
     "title": "Total Chunk Bytes / Interval",
     "type": "gauge",
     "gridPos": { "h": 11, "w": 5, "x": 19, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(stasis_client_operations_recovery_entity_chunk_processed_bytes_total[$__range])) by (step)",
       "legendFormat": "{{step}}"
      }
     ]
    },
    {
     "title": "Decompressed Chunks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "rps" } },
     "targets": [
      {
       "expr": "sum(rate(stasis_client_operations_recovery_entity_chunks_processed_total{step=\"decompressed\"}[$__rate_interval])) by (extra)",
       "legendFormat": "{{step}}"
      }
     ]
    },
    {
     "title": "Decompressed Chunk Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(stasis_client_operations_recovery_entity_chunk_processed_bytes_total{step=\"decompressed\"}[$__rate_interval])) by (extra)",
       "legendFormat": "{{extra}}"
      }
     ]
    },
    {
     "title": "Total Decompressed Chunk Bytes / Interval",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(stasis_client_operations_recovery_entity_chunk_processed_bytes_total{step=\"decompressed\"}[$__range])) by (extra)",
       "legendFormat": "{{extra}}"
      }
     ]
    }
   ]
  }
 ]
}