version: '3'

services:
  identity:
    image: ghcr.io/sndnv/stasis/stasis-identity:dev-latest
    ports:
      - '10000:10000'
      - '10001:10001'
    environment:
      - STASIS_IDENTITY_BOOTSTRAP_MODE=init-and-start
      - STASIS_IDENTITY_BOOTSTRAP_CONFIG=/opt/docker/config/identity-bootstrap.conf
      - STASIS_IDENTITY_LOGLEVEL=DEBUG
      - STASIS_IDENTITY_SERVICE_API_INTERFACE=0.0.0.0
      - STASIS_IDENTITY_SERVICE_API_PORT=10000
      - STASIS_IDENTITY_SERVICE_API_CONTEXT_KEYSTORE_PATH=/opt/docker/certs/identity.p12
      - STASIS_IDENTITY_SERVICE_TELEMETRY_METRICS_INTERFACE=0.0.0.0
      - STASIS_IDENTITY_SERVICE_TELEMETRY_METRICS_PORT=10001
      - STASIS_IDENTITY_TOKENS_REFRESH_ALLOWED=true
      - STASIS_IDENTITY_TOKENS_ACCESS_EXPIRATION=90 minutes
      - STASIS_IDENTITY_UI_DEV_CLIENT_ID=a928359a-e2ee-4db7-9307-8071b2a1c756
      - STASIS_IDENTITY_UI_DEV_REDIRECT_URI=http://localhost:8080/login/callback
      - STASIS_IDENTITY_UI_DEV_CLIENT_SECRET=test-secret
      - STASIS_SERVER_UI_DEV_CLIENT_ID=f8033019-6a7b-46b5-9bda-f2cd240b5538
      - STASIS_SERVER_UI_DEV_REDIRECT_URI=http://localhost:9090/login/callback
      - STASIS_SERVER_UI_DEV_CLIENT_SECRET=test-secret
      - STASIS_SMOKE_TEST_CLIENT_ID=1068208a-3cd7-4121-bad7-050dee3b4494
      - STASIS_SMOKE_TEST_CLIENT_NODE_ID=ef1e47e0-3a55-492e-bf5d-3c09c10c394d
      - STASIS_SMOKE_TEST_CLIENT_SECRET=test-secret
      - STASIS_IDENTITY_UI_DEV_MASTER_PASSWORD=passw0rd
      - STASIS_IDENTITY_UI_DEV_OWNER_PASSWORD=QcilMRSTjZvClf-I6Ac2RA # `passw0rd` - derived with salt `d92beb8f7c3b`
      - STASIS_SERVER_DEV_CLIENT_ID=1c31bd67-cb22-416f-9358-afb5485bca2c
      - STASIS_SERVER_DEV_CLIENT_SECRET=test-server-secret
      - STASIS_SERVER_DEV_TEST_NODE_CLIENT_ID=b4885566-dd69-4b7f-be7f-0568611d1a20
      - STASIS_SERVER_DEV_TEST_NODE_CLIENT_SECRET=test-secret
      - STASIS_SERVER_DEV_TEST_USER_ID=b21c3f0c-0133-4fb5-883d-95ad3aaa1740
      - STASIS_PRIMARY_CLIENT_DEV_CLIENT_ID=d28c5a09-419d-45ff-ad0d-c29faab14f81
      - STASIS_PRIMARY_CLIENT_DEV_CLIENT_NODE_ID=1771f509-8020-4f9b-b4a3-0101e66068de
      - STASIS_PRIMARY_CLIENT_DEV_CLIENT_SECRET=test-secret
      - STASIS_SECONDARY_CLIENT_DEV_CLIENT_ID=13b7c5c5-f625-4dd8-b0c1-704d1fdc1bfa
      - STASIS_SECONDARY_CLIENT_DEV_CLIENT_NODE_ID=744395cd-9084-4c81-89ba-e81c96004223
      - STASIS_SECONDARY_CLIENT_DEV_CLIENT_SECRET=test-secret
      - STASIS_SERVER_DEV_MANAGEMENT_USER_PASSWORD=manage-passw0rd
      - STASIS_MOBILE_CLIENT_DEV_CLIENT_ID=22682c16-0184-40a5-9611-ecb304122a02
      - STASIS_MOBILE_CLIENT_DEV_CLIENT_NODE_ID=ecdd5f59-acaa-4d15-b74b-9fdb57583917
      - STASIS_MOBILE_CLIENT_DEV_CLIENT_SECRET=mobile-secret
      - STASIS_IDENTITY_UI_DEV_MOBILE_USER_PASSWORD=DvoOjDbYhKGDE9YKBcEBcw # `passw0rd` - derived with salt `7e9b9db3dfe6`
      - STASIS_SERVER_DEV_MOBILE_USER_ID=10ef373e-9c79-4066-8341-856db37b9e00
      - PEKKO_HTTP_CORS_ALLOWED_ORIGINS=*
    volumes:
      - ./config/identity-bootstrap.conf:/opt/docker/config/identity-bootstrap.conf
      - ./secrets/identity.p12:/opt/docker/certs/identity.p12

  identity-ui:
    image: ghcr.io/sndnv/stasis/stasis-identity-ui:dev-latest
    ports:
      - '8080:8080'
    environment:
      - IDENTITY_UI_IDENTITY_SERVER=https://localhost:10000
      - IDENTITY_UI_TOKEN_ENDPOINT=/oauth/token
      - IDENTITY_UI_CLIENT_ID=a928359a-e2ee-4db7-9307-8071b2a1c756
      - IDENTITY_UI_REDIRECT_URI=http://localhost:8080/login/callback
      - IDENTITY_UI_SCOPES=urn:stasis:identity:audience:manage-identity
      - IDENTITY_UI_PASSWORD_DERIVATION_ENABLED=true
      - IDENTITY_UI_PASSWORD_DERIVATION_SECRET_SIZE=16
      - IDENTITY_UI_PASSWORD_DERIVATION_ITERATIONS=150000
      - IDENTITY_UI_DERIVATION_SALT_PREFIX=changeme
      - NGINX_SERVER_NAME=localhost
      - NGINX_SERVER_PORT=8080
      - NGINX_CORS_ALLOWED_ORIGIN=*

  server:
    image: ghcr.io/sndnv/stasis/stasis-server:dev-latest
    ports:
      - '20000:20000' # API
      - '20001:20001' # Core
      - '20002:20002' # Bootstrap
      - '20003:20003' # Prometheus
    environment:
      - STASIS_SERVER_SERVICE_BOOTSTRAP_MODE=init-and-start
      - STASIS_SERVER_SERVICE_BOOTSTRAP_CONFIG=/opt/docker/config/server-bootstrap.conf
      - STASIS_SERVER_LOGLEVEL=DEBUG
      - STASIS_SERVER_SERVICE_API_INTERFACE=0.0.0.0
      - STASIS_SERVER_SERVICE_API_PORT=20000
      - STASIS_SERVER_SERVICE_API_CONTEXT_KEYSTORE_PATH=/opt/docker/certs/server.p12
      - STASIS_SERVER_SERVICE_CORE_INTERFACE=0.0.0.0
      - STASIS_SERVER_SERVICE_CORE_PORT=20001
      - STASIS_SERVER_SERVICE_TELEMETRY_METRICS_INTERFACE=0.0.0.0
      - STASIS_SERVER_SERVICE_TELEMETRY_METRICS_PORT=20003
      - STASIS_SERVER_CREDENTIALS_MANAGERS_IDENTITY_URL=https://identity:10000
      - STASIS_SERVER_CREDENTIALS_MANAGERS_IDENTITY_MANAGEMENT_USER=server-management-user
      - STASIS_SERVER_CREDENTIALS_MANAGERS_IDENTITY_MANAGEMENT_USER_PASSWORD=manage-passw0rd
      - STASIS_SERVER_CREDENTIALS_MANAGERS_IDENTITY_MANAGEMENT_SCOPE=urn:stasis:identity:audience:manage-identity
      - STASIS_SERVER_CREDENTIALS_MANAGERS_IDENTITY_CONTEXT_ENABLED=true
      - STASIS_SERVER_CREDENTIALS_MANAGERS_IDENTITY_CONTEXT_TRUSTSTORE_PATH=/opt/docker/certs/identity.p12
      - STASIS_SERVER_BOOTSTRAP_API_INTERFACE=0.0.0.0
      - STASIS_SERVER_BOOTSTRAP_API_PORT=20002
      - STASIS_SERVER_BOOTSTRAP_DEVICES_PARAMETERS_SERVER_API_URL=https://server:20000
      - STASIS_SERVER_BOOTSTRAP_DEVICES_PARAMETERS_SERVER_API_CONTEXT_ENABLED=true
      - STASIS_SERVER_BOOTSTRAP_DEVICES_PARAMETERS_SERVER_CORE_ADDRESS=https://server:20001
      - STASIS_SERVER_BOOTSTRAP_DEVICES_PARAMETERS_SERVER_CORE_CONTEXT_ENABLED=true
      - STASIS_SERVER_SERVICE_CORE_CONTEXT_KEYSTORE_PATH=/opt/docker/certs/server.p12
      - STASIS_SERVER_CLIENTS_AUTHENTICATION_CONTEXT_ENABLED=true
      - STASIS_SERVER_CLIENTS_AUTHENTICATION_CONTEXT_TRUSTSTORE_PATH=/opt/docker/certs/identity.p12
      - STASIS_SERVER_AUTHENTICATORS_USERS_AUDIENCE=server-api
      - STASIS_SERVER_AUTHENTICATORS_USERS_JWKS_ENDPOINT=https://identity:10000/jwks/jwks.json
      - STASIS_SERVER_AUTHENTICATORS_NODES_AUDIENCE=b4885566-dd69-4b7f-be7f-0568611d1a20
      - STASIS_SERVER_AUTHENTICATORS_NODES_JWKS_ENDPOINT=https://identity:10000/jwks/jwks.json
      - STASIS_SERVER_AUTHENTICATORS_INSTANCE_TOKEN_ENDPOINT=https://identity:10000/oauth/token
      - STASIS_SERVER_AUTHENTICATORS_INSTANCE_CLIENT_ID=1c31bd67-cb22-416f-9358-afb5485bca2c
      - STASIS_SERVER_AUTHENTICATORS_INSTANCE_CLIENT_SECRET=test-server-secret
      - STASIS_SERVER_AUTHENTICATORS_INSTANCE_USE_QUERY_STRING=true
      - STASIS_SERVER_PERSISTENCE_STAGING_ENABLED=false
      - STASIS_SERVER_PERSISTENCE_STAGING_STORE_TYPE=memory
      - STASIS_SERVER_PERSISTENCE_STAGING_STORE_MEMORY_MAX_SIZE=1M
      - STASIS_SERVER_DEV_PRIMARY_TEST_DEVICE_ID=519e0c7b-43d0-4df5-890a-dd0d86f56072
      - STASIS_SERVER_DEV_PRIMARY_TEST_DEVICE_NODE_ID=1771f509-8020-4f9b-b4a3-0101e66068de
      - STASIS_SERVER_DEV_SECONDARY_TEST_DEVICE_ID=7dee7457-da81-48bb-aae0-7cfdb1f827a8
      - STASIS_SERVER_DEV_SECONDARY_TEST_DEVICE_NODE_ID=744395cd-9084-4c81-89ba-e81c96004223
      - STASIS_SERVER_DEV_TEST_USER_ID=b21c3f0c-0133-4fb5-883d-95ad3aaa1740
      - STASIS_SERVER_DEV_TEST_USER_SALT=d92beb8f7c3b
      - STASIS_SMOKE_TEST_CLIENT_NODE_ID=ef1e47e0-3a55-492e-bf5d-3c09c10c394d
      - STASIS_SERVER_DEV_MOBILE_DEVICE_ID=570c237e-0507-47d7-b90b-8a9a3947fcbc
      - STASIS_SERVER_DEV_MOBILE_USER_ID=10ef373e-9c79-4066-8341-856db37b9e00
      - STASIS_SERVER_DEV_MOBILE_USER_SALT=7e9b9db3dfe6
      - STASIS_SERVER_DEV_MOBILE_DEVICE_NODE_ID=ecdd5f59-acaa-4d15-b74b-9fdb57583917
      - PEKKO_HTTP_PARSING_MAX_CONTENT_LENGTH=4G
      - PEKKO_HTTP_CORS_ALLOWED_ORIGINS=*
    volumes:
      - ./config/server-bootstrap.conf:/opt/docker/config/server-bootstrap.conf
      - ./secrets/identity.p12:/opt/docker/certs/identity.p12
      - ./secrets/server.p12:/opt/docker/certs/server.p12

  server-ui:
    image: ghcr.io/sndnv/stasis/stasis-server-ui:dev-latest
    ports:
      - '9090:9090'
    environment:
      - SERVER_UI_SERVER_API=https://localhost:20000
      - SERVER_UI_BOOTSTRAP_API=https://localhost:20002
      - SERVER_UI_AUTHORIZATION_ENDPOINT=http://localhost:8080/login/authorize
      - SERVER_UI_TOKEN_ENDPOINT=https://localhost:10000/oauth/token
      - SERVER_UI_CLIENT_ID=f8033019-6a7b-46b5-9bda-f2cd240b5538
      - SERVER_UI_REDIRECT_URI=http://localhost:9090/login/callback
      - SERVER_UI_SCOPES=urn:stasis:identity:audience:server-api
      - SERVER_UI_PASSWORD_DERIVATION_ENABLED=true
      - SERVER_UI_PASSWORD_DERIVATION_SECRET_SIZE=16
      - SERVER_UI_PASSWORD_DERIVATION_ITERATIONS=150000
      - SERVER_UI_DERIVATION_SALT_PREFIX=changeme
      - NGINX_SERVER_NAME=localhost
      - NGINX_SERVER_PORT=9090
      - NGINX_CORS_ALLOWED_ORIGIN=*

  primary-client:
    image: stasis-client-cli:dev-latest
    command: tail -F /home/demiourgos728/stasis-client/logs/stasis-client.log
    tty: true
    environment:
      - STASIS_CLIENT_LOGLEVEL=INFO
      - STASIS_CLIENT_API_HTTP_INTERFACE=localhost
      - STASIS_CLIENT_API_HTTP_PORT=9090
      - STASIS_CLIENT_API_HTTP_CONTEXT_ENABLED=true
      - STASIS_CLIENT_API_HTTP_CONTEXT_KEYSTORE_PATH=/home/demiourgos728/.config/stasis-client/certs/client.p12
      - STASIS_CLIENT_API_INIT_INTERFACE=localhost
      - STASIS_CLIENT_API_INIT_PORT=9091
      - STASIS_CLIENT_API_INIT_CONTEXT_ENABLED=true
      - STASIS_CLIENT_API_INIT_CONTEXT_KEYSTORE_PATH=/home/demiourgos728/.config/stasis-client/certs/client.p12
      - STASIS_CLIENT_SERVER_AUTHENTICATION_TOKEN_ENDPOINT=https://identity:10000/oauth/token
      - STASIS_CLIENT_SERVER_AUTHENTICATION_CLIENT_ID=d28c5a09-419d-45ff-ad0d-c29faab14f81
      - STASIS_CLIENT_SERVER_AUTHENTICATION_CLIENT_SECRET=test-secret
      - STASIS_CLIENT_SERVER_AUTHENTICATION_USE_QUERY_STRING=true
      - STASIS_CLIENT_SERVER_AUTHENTICATION_SCOPES_API=urn:stasis:identity:audience:server-api
      - STASIS_CLIENT_SERVER_AUTHENTICATION_SCOPES_CORE=urn:stasis:identity:audience:b4885566-dd69-4b7f-be7f-0568611d1a20
      - STASIS_CLIENT_SERVER_AUTHENTICATION_CONTEXT_ENABLED=true
      - STASIS_CLIENT_SERVER_AUTHENTICATION_CONTEXT_TRUSTSTORE_PATH=/home/demiourgos728/.config/stasis-client/certs/identity.p12
      - STASIS_CLIENT_SERVER_API_URL=https://server:20000
      - STASIS_CLIENT_SERVER_API_USER=b21c3f0c-0133-4fb5-883d-95ad3aaa1740
      - STASIS_CLIENT_SERVER_API_USER_SALT=d92beb8f7c3b
      - STASIS_CLIENT_SERVER_API_DEVICE=519e0c7b-43d0-4df5-890a-dd0d86f56072
      - STASIS_CLIENT_SERVER_API_CONTEXT_ENABLED=true
      - STASIS_CLIENT_SERVER_API_CONTEXT_TRUSTSTORE_PATH=/home/demiourgos728/.config/stasis-client/certs/server.p12
      - STASIS_CLIENT_SERVER_CORE_ADDRESS=https://server:20001
      - STASIS_CLIENT_SERVER_CORE_NODE_ID=1771f509-8020-4f9b-b4a3-0101e66068de
      - STASIS_CLIENT_SERVER_CORE_CONTEXT_ENABLED=true
      - STASIS_CLIENT_SERVER_CORE_CONTEXT_TRUSTSTORE_PATH=/home/demiourgos728/.config/stasis-client/certs/server.p12
      - STASIS_CLIENT_OPS_BACKUP_RULES_FILES=client.rules
      - STASIS_CLIENT_OPS_BACKUP_MAX_CHUNK_SIZE=8K
      - STASIS_CLIENT_OPS_BACKUP_MAX_PART_SIZE=128M
      - STASIS_CLIENT_OPS_SCHEDULING_SCHEDULES_FILE=client.schedules
      - STASIS_CLIENT_OPS_SCHEDULING_MIN_DELAY=30 seconds
      - STASIS_CLIENT_OPS_SCHEDULING_MAX_EXTRA_DELAY=5 minutes
      - STASIS_CLIENT_OPS_MONITORING_INTERVAL=10 seconds
    volumes:
      - ./secrets/localhost.p12:/home/demiourgos728/.config/stasis-client/certs/client.p12
      - ./secrets/identity.p12:/home/demiourgos728/.config/stasis-client/certs/identity.p12
      - ./secrets/server.p12:/home/demiourgos728/.config/stasis-client/certs/server.p12
      - ./config/client.conf:/home/demiourgos728/.config/stasis-client/client.conf
      - ./config/client.rules:/home/demiourgos728/.config/stasis-client/client.rules
      - ./config/client.schedules:/home/demiourgos728/.config/stasis-client/client.schedules
      - ./secrets/client.secret:/home/demiourgos728/.config/stasis-client/device-secret

  secondary-client:
    image: stasis-client-cli:dev-latest
    command: tail -F /home/demiourgos728/stasis-client/logs/stasis-client.log
    tty: true

  prometheus:
    image: prom/prometheus
    ports:
      - "19090:9090"
    volumes:
      - ./config/prometheus:/etc/prometheus

  grafana:
    image: grafana/grafana
    ports:
      - "13000:3000"
    volumes:
      - ./config/grafana:/etc/grafana/provisioning
      - ../grafana/dashboards/identity:/etc/grafana/provisioning/dashboards/identity
      - ../grafana/dashboards/server:/etc/grafana/provisioning/dashboards/server
      - ../grafana/dashboards/jvm:/etc/grafana/provisioning/dashboards/jvm
