version: '3'

services:
  identity:
    image: identity:0.0.1-SNAPSHOT
    ports:
      - '9090:9090'
    environment:
      - IDENTITY_BOOTSTRAP_ENABLED=true
      - IDENTITY_BOOTSTRAP_CONFIG=/opt/docker/config/identity-bootstrap.conf
      - IDENTITY_LOGLEVEL=DEBUG
      - IDENTITY_SERVICE_INTERFACE=0.0.0.0
      - IDENTITY_SERVICE_PORT=9090
      - IDENTITY_SERVICE_CONTEXT_KEYSTORE_PATH=/opt/docker/certs/identity.p12
      - IDENTITY_TOKENS_REFRESH_ALLOWED=true
      - IDENTITY_UI_DEV_CLIENT_ID=a928359a-e2ee-4db7-9307-8071b2a1c756
      - IDENTITY_UI_DEV_REDIRECT_URI=https://localhost:8080/manage/login/callback
      - IDENTITY_UI_DEV_CLIENT_SECRET=test-secret
      - IDENTITY_UI_DEV_OWNER_PASSWORD=passw0rd
      - SERVER_DEV_CLIENT_ID=1c31bd67-cb22-416f-9358-afb5485bca2c
      - SERVER_DEV_CLIENT_SECRET=test-server-secret
      - SERVER_DEV_TEST_NODE_CLIENT_ID=b4885566-dd69-4b7f-be7f-0568611d1a20
      - SERVER_DEV_TEST_NODE_CLIENT_SECRET=test-secret
      - SERVER_DEV_TEST_USER_ID=b21c3f0c-0133-4fb5-883d-95ad3aaa1740
    volumes:
      - ./identity-bootstrap.conf:/opt/docker/config/identity-bootstrap.conf
      - ./certs/identity.p12:/opt/docker/certs/identity.p12

  identity-ui:
    image: identity-ui:dev-latest
    command: /bin/sh -c "yarn serve"
    ports:
      - '8080:8080'
    environment:
      - IDENTITY_UI_API_URL=https://localhost:8080
      - IDENTITY_UI_AUTH_CLIENT_ID=a928359a-e2ee-4db7-9307-8071b2a1c756
      - IDENTITY_UI_AUTH_REDIRECT_URI=https://localhost:8080/manage/login/callback

  server:
    image: server:0.0.1-SNAPSHOT
    ports:
      - '19090:9090'
      - '19091:9091'
    environment:
      - SERVER_BOOTSTRAP_ENABLED=true
      - SERVER_BOOTSTRAP_CONFIG=/opt/docker/config/server-bootstrap.conf
      - SERVER_LOGLEVEL=DEBUG
      - SERVER_SERVICE_API_INTERFACE=0.0.0.0
      - SERVER_SERVICE_API_PORT=9090
      - SERVER_SERVICE_API_CONTEXT_KEYSTORE_PATH=/opt/docker/certs/server.p12
      - SERVER_SERVICE_CORE_INTERFACE=0.0.0.0
      - SERVER_SERVICE_CORE_PORT=9091
      - SERVER_SERVICE_CORE_CONTEXT_KEYSTORE_PATH=/opt/docker/certs/server.p12
      - SERVER_CLIENTS_AUTHENTICATION_CONTEXT_ENABLED=true
      - SERVER_CLIENTS_AUTHENTICATION_CONTEXT_TRUSTSTORE_PATH=/opt/docker/certs/identity.p12
      - SERVER_AUTHENTICATORS_USERS_AUDIENCE=server-api
      - SERVER_AUTHENTICATORS_USERS_JWKS_ENDPOINT=https://identity:9090/jwks/jwks.json
      - SERVER_AUTHENTICATORS_NODES_AUDIENCE=b4885566-dd69-4b7f-be7f-0568611d1a20
      - SERVER_AUTHENTICATORS_NODES_JWKS_ENDPOINT=https://identity:9090/jwks/jwks.json
      - SERVER_AUTHENTICATORS_INSTANCE_TOKEN_ENDPOINT=https://identity:9090/oauth/token
      - SERVER_AUTHENTICATORS_INSTANCE_CLIENT_ID=1c31bd67-cb22-416f-9358-afb5485bca2c
      - SERVER_AUTHENTICATORS_INSTANCE_CLIENT_SECRET=test-server-secret
      - SERVER_PERSISTENCE_STAGING_ENABLED=false
      - SERVER_PERSISTENCE_STAGING_STORE_TYPE=memory
      - SERVER_PERSISTENCE_STAGING_STORE_MEMORY_MAX_SIZE=1M
      - SERVER_DEV_TEST_DEVICE_ID=519e0c7b-43d0-4df5-890a-dd0d86f56072
      - SERVER_DEV_TEST_DEVICE_NODE_ID=e264b6bf-13f4-425e-a92c-be0b6b53fb7d
      - SERVER_DEV_TEST_USER_ID=b21c3f0c-0133-4fb5-883d-95ad3aaa1740
    volumes:
      - ./server-bootstrap.conf:/opt/docker/config/server-bootstrap.conf
      - ./certs/identity.p12:/opt/docker/certs/identity.p12
      - ./certs/server.p12:/opt/docker/certs/server.p12
