matrix:
  include:
    - language: scala
      scala:
        - "2.13.2"
      jdk:
        - openjdk11
      before_install:
        - mkdir $TRAVIS_BUILD_DIR/target
      script:
        - sbt ++$TRAVIS_SCALA_VERSION qa
      after_success:
        - sbt coveralls

    - language: node_js
      node_js:
        - "12"
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
        - export PATH=$HOME/.yarn/bin:$PATH
        - cd identity-ui
        - yarn install
      cache:
        directories:
          - node_modules
      script:
        - yarn lint
        - yarn test

    - language: python
      python:
        - '3.8'
      before_install:
        - cd client-cli
        - pip install -e .
        - pip install coverage pylint
      script:
        - ./qa.py
