language: scala

scala:
  - 2.12.7

branches:
  only:
    - master

script:
  - sbt ++$TRAVIS_SCALA_VERSION compile test:compile
  - sbt ++$TRAVIS_SCALA_VERSION "project stasis" coverage "testOnly stasis.test.specs.*"
  - sbt ++$TRAVIS_SCALA_VERSION "project stasis" coverageReport
  - sbt ++$TRAVIS_SCALA_VERSION coverageAggregate

after_success:
  - sbt coveralls

