version: '3'

services:
  identity:
    image: stasis-identity:dev-latest
    ports:
      - '10000:10000'
    environment:
      - STASIS_IDENTITY_BOOTSTRAP_ENABLED=true
      - STASIS_IDENTITY_BOOTSTRAP_CONFIG=/opt/docker/config/identity-bootstrap.conf
      - STASIS_IDENTITY_LOGLEVEL=DEBUG
      - STASIS_IDENTITY_SERVICE_API_INTERFACE=0.0.0.0
      - STASIS_IDENTITY_SERVICE_API_PORT=10000
      - STASIS_IDENTITY_SERVICE_API_CONTEXT_ENABLED=false
      - STASIS_IDENTITY_TOKENS_REFRESH_ALLOWED=true
      - STASIS_IDENTITY_TOKENS_ACCESS_EXPIRATION=90 minutes
      - STASIS_IDENTITY_UI_DEV_CLIENT_ID=a928359a-e2ee-4db7-9307-8071b2a1c756
      - STASIS_IDENTITY_UI_DEV_REDIRECT_URI=http://localhost:11000/login/callback
      - STASIS_IDENTITY_UI_DEV_CLIENT_SECRET=test-secret
      - STASIS_SERVER_UI_DEV_CLIENT_ID=f8033019-6a7b-46b5-9bda-f2cd240b5538
      - STASIS_SERVER_UI_DEV_REDIRECT_URI=http://localhost:8080/login/callback
      - STASIS_SERVER_UI_DEV_CLIENT_SECRET=test-secret
      - STASIS_IDENTITY_UI_DEV_MASTER_PASSWORD=passw0rd
      - STASIS_IDENTITY_UI_DEV_OWNER_PASSWORD=QcilMRSTjZvClf-I6Ac2RA # `passw0rd` - derived with salt `d92beb8f7c3b`
      - STASIS_SERVER_DEV_CLIENT_ID=1c31bd67-cb22-416f-9358-afb5485bca2c
      - STASIS_SERVER_DEV_CLIENT_SECRET=test-server-secret
      - STASIS_SERVER_DEV_TEST_USER_ID=b21c3f0c-0133-4fb5-883d-95ad3aaa1740
      - STASIS_SERVER_DEV_MANAGEMENT_USER_PASSWORD=manage-passw0rd
      - AKKA_HTTP_CORS_ALLOWED_ORIGINS=*
    volumes:
      - ./identity-bootstrap.conf:/opt/docker/config/identity-bootstrap.conf

  identity-ui:
    image: stasis-identity-ui:dev-latest
    ports:
      - '11000:11000'
    environment:
      - IDENTITY_UI_IDENTITY_SERVER=http://localhost:10000
      - IDENTITY_UI_TOKEN_ENDPOINT=/oauth/token
      - IDENTITY_UI_CLIENT_ID=a928359a-e2ee-4db7-9307-8071b2a1c756
      - IDENTITY_UI_REDIRECT_URI=http://localhost:11000/login/callback
      - IDENTITY_UI_SCOPES=urn:stasis:identity:audience:manage-identity
      - IDENTITY_UI_PASSWORD_DERIVATION_ENABLED=true
      - IDENTITY_UI_PASSWORD_DERIVATION_SECRET_SIZE=16
      - IDENTITY_UI_PASSWORD_DERIVATION_ITERATIONS=150000
      - IDENTITY_UI_DERIVATION_SALT_PREFIX=changeme
      - NGINX_SERVER_NAME=localhost
      - NGINX_SERVER_PORT=11000
      - NGINX_CORS_ALLOWED_ORIGIN=*

  server:
    image: stasis-server:dev-latest
    ports:
      - '20000:20000' # API
      - '20001:20001' # Core
      - '20002:20002' # Bootstrap
    environment:
      - STASIS_SERVER_SERVICE_BOOTSTRAP_ENABLED=true
      - STASIS_SERVER_SERVICE_BOOTSTRAP_CONFIG=/opt/docker/config/server-bootstrap.conf
      - STASIS_SERVER_LOGLEVEL=DEBUG
      - STASIS_SERVER_SERVICE_API_INTERFACE=0.0.0.0
      - STASIS_SERVER_SERVICE_API_PORT=20000
      - STASIS_SERVER_SERVICE_API_CONTEXT_ENABLED=false
      - STASIS_SERVER_SERVICE_CORE_INTERFACE=0.0.0.0
      - STASIS_SERVER_SERVICE_CORE_PORT=20001
      - STASIS_SERVER_SERVICE_CORE_CONTEXT_ENABLED=false
      - STASIS_SERVER_CREDENTIALS_MANAGERS_IDENTITY_URL=http://identity:10000
      - STASIS_SERVER_CREDENTIALS_MANAGERS_IDENTITY_MANAGEMENT_USER=server-management-user
      - STASIS_SERVER_CREDENTIALS_MANAGERS_IDENTITY_MANAGEMENT_USER_PASSWORD=manage-passw0rd
      - STASIS_SERVER_CREDENTIALS_MANAGERS_IDENTITY_MANAGEMENT_SCOPE=urn:stasis:identity:audience:manage-identity
      - STASIS_SERVER_CREDENTIALS_MANAGERS_IDENTITY_CONTEXT_ENABLED=false
      - STASIS_SERVER_BOOTSTRAP_API_INTERFACE=0.0.0.0
      - STASIS_SERVER_BOOTSTRAP_API_PORT=20002
      - STASIS_SERVER_BOOTSTRAP_DEVICES_PARAMETERS_SERVER_API_URL=http://server:20000
      - STASIS_SERVER_BOOTSTRAP_DEVICES_PARAMETERS_SERVER_API_CONTEXT_ENABLED=false
      - STASIS_SERVER_BOOTSTRAP_DEVICES_PARAMETERS_SERVER_CORE_ADDRESS=http://server:20001
      - STASIS_SERVER_BOOTSTRAP_DEVICES_PARAMETERS_SERVER_CORE_CONTEXT_ENABLED=false
      - STASIS_SERVER_CLIENTS_AUTHENTICATION_CONTEXT_ENABLED=false
      - STASIS_SERVER_AUTHENTICATORS_USERS_AUDIENCE=server-api
      - STASIS_SERVER_AUTHENTICATORS_USERS_JWKS_ENDPOINT=http://identity:10000/jwks/jwks.json
      - STASIS_SERVER_AUTHENTICATORS_NODES_AUDIENCE=b4885566-dd69-4b7f-be7f-0568611d1a20
      - STASIS_SERVER_AUTHENTICATORS_NODES_JWKS_ENDPOINT=http://identity:10000/jwks/jwks.json
      - STASIS_SERVER_AUTHENTICATORS_INSTANCE_TOKEN_ENDPOINT=http://identity:10000/oauth/token
      - STASIS_SERVER_AUTHENTICATORS_INSTANCE_CLIENT_ID=1c31bd67-cb22-416f-9358-afb5485bca2c
      - STASIS_SERVER_AUTHENTICATORS_INSTANCE_CLIENT_SECRET=test-server-secret
      - STASIS_SERVER_AUTHENTICATORS_INSTANCE_USE_QUERY_STRING=true
      - STASIS_SERVER_PERSISTENCE_STAGING_ENABLED=false
      - STASIS_SERVER_DEV_PRIMARY_TEST_DEVICE_ID=519e0c7b-43d0-4df5-890a-dd0d86f56072
      - STASIS_SERVER_DEV_PRIMARY_TEST_DEVICE_NODE_ID=1771f509-8020-4f9b-b4a3-0101e66068de
      - STASIS_SERVER_DEV_SECONDARY_TEST_DEVICE_ID=7dee7457-da81-48bb-aae0-7cfdb1f827a8
      - STASIS_SERVER_DEV_SECONDARY_TEST_DEVICE_NODE_ID=744395cd-9084-4c81-89ba-e81c96004223
      - STASIS_SERVER_DEV_TEST_USER_ID=b21c3f0c-0133-4fb5-883d-95ad3aaa1740
      - STASIS_SERVER_DEV_TEST_USER_SALT=d92beb8f7c3b
      - STASIS_SMOKE_TEST_CLIENT_NODE_ID=ef1e47e0-3a55-492e-bf5d-3c09c10c394d
      - AKKA_HTTP_PARSING_MAX_CONTENT_LENGTH=4G
      - AKKA_HTTP_CORS_ALLOWED_ORIGINS=*
    volumes:
      - ./server-bootstrap.conf:/opt/docker/config/server-bootstrap.conf
