{
 "title": "APIs",
 "tags": [ "identity" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "endpoint",
    "label": "Endpoint",
    "query": {
     "query": "stasis_identity_endpoints_requests_total"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(stasis_identity_endpoints_requests_total{endpoint=~\"$endpoint\"}[$__rate_interval])) by (endpoint, method)",
     "legendFormat": "[{{endpoint}}] - {{method}}"
    }
   ]
  },
  {
   "title": "Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(stasis_identity_endpoints_response_times_count{endpoint=~\"$endpoint\"}[$__rate_interval])) by (endpoint, method, status)",
     "legendFormat": "{{endpoint}} - [{{method}}] / [{{status}}]"
    },
    {}
   ]
  },
  {
   "title": "Response Times",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(stasis_identity_endpoints_response_times_bucket{endpoint=~\"$endpoint\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}