{
 "title": "Overview",
 "tags": [ "identity" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Persistence / Key-Value Stores", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Operations",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(stasis_identity_persistence_kv_put_operations_total[$__rate_interval])) by (backend)",
     "legendFormat": "[{{backend}}] - Put"
    },
    {
     "expr": "sum(rate(stasis_identity_persistence_kv_get_operations_total[$__rate_interval])) by (backend)",
     "legendFormat": "[{{backend}}] - Get"
    },
    {
     "expr": "sum(rate(stasis_identity_persistence_kv_delete_operations_total[$__rate_interval])) by (backend)",
     "legendFormat": "[{{backend}}] - Delete"
    },
    {
     "expr": "sum(rate(stasis_identity_persistence_kv_init_operations_total[$__rate_interval])) by (backend)",
     "legendFormat": "[{{backend}}] - Init"
    },
    {
     "expr": "sum(rate(stasis_identity_persistence_kv_drop_operations_total[$__rate_interval])) by (backend)",
     "legendFormat": "[{{backend}}] - Drop"
    }
   ]
  },
  { "title": "APIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(stasis_identity_endpoints_requests_total[$__rate_interval])) by (endpoint, method)",
     "legendFormat": "[{{method}}] - {{endpoint}}"
    }
   ]
  },
  {
   "title": "Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(stasis_identity_endpoints_response_times_count[$__rate_interval])) by (endpoint, method, status)",
     "legendFormat": "[{{method}}] - [{{status}}] - {{endpoint}}"
    },
    {}
   ]
  },
  {
   "title": "Response Times",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(stasis_identity_endpoints_response_times_bucket[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Security", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Authenticators",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(stasis_identity_authenticators_authentication_successful_total[$__rate_interval])) by (authenticator)",
     "legendFormat": "{{authenticator}}"
    },
    {
     "expr": "sum(rate(stasis_identity_authenticators_authentication_failed_total[$__rate_interval])) by (authenticator)",
     "legendFormat": "{{authenticator}}"
    }
   ]
  }
 ]
}