{
 "title": "Overview",
 "tags": [ "jvm" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "jvm_threads_state" } },
   { "name": "pool", "label": "Pool", "query": { "query": "jvm_memory_pool_bytes_init" } }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=~\"$job\"}[1m]) * 60) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(process_resident_memory_bytes{job=~\"$job\"}[$__rate_interval])) by (job)",
     "legendFormat": "Residen [{{job}}]"
    },
    {
     "expr": "sum(rate(process_virtual_memory_bytes{job=~\"$job\"}[$__rate_interval])) by (job)",
     "legendFormat": "Virtual [{{job}}]"
    }
   ]
  },
  {
   "title": "Open Files",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_init{area=\"heap\",job=~\"$job\"}) by (job)",
     "legendFormat": "Initial [{{job}}]"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{area=\"heap\",job=~\"$job\"}) by (job)",
     "legendFormat": "Max [{{job}}]"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{area=\"heap\",job=~\"$job\"}) by (job)",
     "legendFormat": "Current [{{job}}]"
    }
   ]
  },
  {
   "title": "Non-Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_init{area=\"nonheap\",job=~\"$job\"}) by (job)",
     "legendFormat": "Initial [{{job}}]"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{area=\"nonheap\",job=~\"$job\"}) by (job)",
     "legendFormat": "Max [{{job}}]"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{area=\"nonheap\",job=~\"$job\"}) by (job)",
     "legendFormat": "Current [{{job}}]"
    }
   ]
  },
  {
   "title": "Loaded Classes",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_classes_currently_loaded{job=~\"$job\"}) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "JVM Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(jvm_threads_state{job=~\"$job\"}) by (state, job)",
     "legendFormat": "[{{job}}] {{state}}"
    }
   ]
  },
  {
   "title": "Total",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_threads_peak{job=~\"$job\"}) by (job)",
     "legendFormat": "Peak [{{job}}]"
    },
    {
     "expr": "sum(jvm_threads_current{job=~\"$job\"}) by (job)",
     "legendFormat": "Current [{{job}}]"
    },
    {
     "expr": "sum(jvm_threads_daemon{job=~\"$job\"}) by (job)",
     "legendFormat": "Daemon [{{job}}]"
    }
   ]
  },
  {
   "title": "Deadlocked",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_threads_deadlocked{job=~\"$job\"}) by (job)",
     "legendFormat": "Deadlocked [{{job}}]"
    },
    {
     "expr": "sum(jvm_threads_deadlocked_monitor{job=~\"$job\"}) by (job)",
     "legendFormat": "Deadlocked / Monitor [{{job}}]"
    }
   ]
  },
  { "title": "JVM Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Bytes / Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_pool_bytes_init{job=~\"$job\", pool=~\"$pool\"}) by (job)",
     "legendFormat": "Initial [{{job}}]"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_max{job=~\"$job\", pool=~\"$pool\"}) by (job)",
     "legendFormat": "Max [{{job}}]"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_used{job=~\"$job\", pool=~\"$pool\"}) by (job)",
     "legendFormat": "Used [{{job}}]"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_committed{job=~\"$job\", pool=~\"$pool\"}) by (job)",
     "legendFormat": "Committed [{{job}}]"
    }
   ]
  },
  {
   "title": "Bytes / Allocated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_pool_allocated_bytes_total{job=~\"$job\", pool=~\"$pool\"}) by (pool, job)",
     "legendFormat": "[{{job}}] {{pool}}"
    }
   ]
  },
  {
   "title": "Bytes / Initial",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_pool_bytes_init{job=~\"$job\", pool=~\"$pool\"}) by (pool, job)",
     "legendFormat": "[{{job}}] {{pool}}"
    }
   ]
  },
  {
   "title": "Bytes / Max",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_pool_bytes_max{job=~\"$job\", pool=~\"$pool\"}) by (pool, job)",
     "legendFormat": "[{{job}}] {{pool}}"
    }
   ]
  },
  {
   "title": "Bytes / Committed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_pool_bytes_committed{job=~\"$job\", pool=~\"$pool\"}) by (pool, job)",
     "legendFormat": "[{{job}}] {{pool}}"
    }
   ]
  },
  {
   "title": "Bytes / Used",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_pool_bytes_used{job=~\"$job\", pool=~\"$pool\"}) by (pool, job)",
     "legendFormat": "[{{job}}] {{pool}}"
    }
   ]
  },
  {
   "title": "Collection / Initial",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_pool_collection_init_bytes{job=~\"$job\", pool=~\"$pool\"}) by (pool, job)",
     "legendFormat": "[{{job}}] {{pool}}"
    }
   ]
  },
  {
   "title": "Collection / Max",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_pool_collection_max_bytes{job=~\"$job\", pool=~\"$pool\"}) by (pool, job)",
     "legendFormat": "[{{job}}] {{pool}}"
    }
   ]
  },
  {
   "title": "Collection / Committed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_pool_collection_committed_bytes{job=~\"$job\", pool=~\"$pool\"}) by (pool, job)",
     "legendFormat": "[{{job}}] {{pool}}"
    }
   ]
  },
  {
   "title": "Collection / Used",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_pool_collection_used_bytes{job=~\"$job\", pool=~\"$pool\"}) by (pool, job)",
     "legendFormat": "[{{job}}] {{pool}}"
    }
   ]
  }
 ]
}