name: server_ui
description: Web-based user interface for the `server` service.
version: 0.0.1-SNAPSHOT

publish_to: 'none'

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  http: ^0.13.5
  oauth2: ^2.0.1
  url_launcher: ^6.1.9
  fluro: ^2.0.4
  url_strategy: ^0.2.0
  shared_preferences: ^2.0.17
  flutter_svg: ^2.0.0+1
  flutter_dotenv: ^5.0.2
  data_table_2: ^2.3.12
  intl: ^0.18.0
  multi_select_flutter: ^4.1.3
  cryptography: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  freezed: ^2.2.0
  json_serializable: ^6.6.1
  mockito: ^5.3.2

flutter:
  uses-material-design: true
