name: server_ui
description: Web-based user interface for the `server` service.
version: 1.0.0

publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  http: ^0.13.5
  oauth2: ^2.0.2
  url_launcher: ^6.1.14
  fluro: ^2.0.5
  url_strategy: ^0.2.0
  shared_preferences: ^2.2.1
  flutter_svg: ^2.0.7
  flutter_dotenv: ^5.1.0
  data_table_2: ^2.5.8
  intl: ^0.18.1
  multi_select_flutter: ^4.1.3
  cryptography: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  mockito: ^5.4.2

flutter:
  uses-material-design: true
