addSbtPlugin("org.scoverage"           % "sbt-scoverage"       % "1.9.3")
addSbtPlugin("org.scoverage"           % "sbt-coveralls"       % "1.3.1")
addSbtPlugin("org.scalameta"           % "sbt-scalafmt"        % "2.4.6")
addSbtPlugin("org.wartremover"         % "sbt-wartremover"     % "2.4.18")
addSbtPlugin("com.lightbend.akka.grpc" % "sbt-akka-grpc"       % "2.1.3")
addSbtPlugin("com.github.sbt"          % "sbt-native-packager" % "1.9.9")
addSbtPlugin("com.timushev.sbt"        % "sbt-updates"         % "0.6.2")
