addSbtPlugin("org.scoverage"    % "sbt-scoverage"         % "2.4.3")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"          % "2.5.6")
addSbtPlugin("org.wartremover"  % "sbt-wartremover"       % "3.5.0")
addSbtPlugin("org.apache.pekko" % "pekko-grpc-sbt-plugin" % "1.2.0")
addSbtPlugin("com.github.sbt"   % "sbt-native-packager"   % "1.11.4")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"           % "0.6.3")
addSbtPlugin("com.eed3si9n"     % "sbt-buildinfo"         % "0.13.1")
