addSbtPlugin("org.scoverage"    % "sbt-scoverage"         % "2.1.0")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"          % "2.5.2")
addSbtPlugin("org.wartremover"  % "sbt-wartremover"       % "3.1.6")
addSbtPlugin("org.apache.pekko" % "pekko-grpc-sbt-plugin" % "1.0.2")
addSbtPlugin("com.github.sbt"   % "sbt-native-packager"   % "1.10.4")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"           % "0.6.3")
addSbtPlugin("com.eed3si9n"     % "sbt-buildinfo"         % "0.12.0")
