version: '3'

services:
  identity:
    image: stasis-identity:dev-latest
    ports:
      - '10000:10000'
    environment:
      - STASIS_IDENTITY_BOOTSTRAP_ENABLED=true
      - STASIS_IDENTITY_BOOTSTRAP_CONFIG=/opt/docker/config/bootstrap.conf
      - STASIS_IDENTITY_LOGLEVEL=DEBUG
      - STASIS_IDENTITY_SERVICE_INTERFACE=0.0.0.0
      - STASIS_IDENTITY_SERVICE_PORT=10000
      - STASIS_IDENTITY_SERVICE_CONTEXT_KEYSTORE_PATH=/opt/docker/certs/localhost.p12
      - STASIS_IDENTITY_TOKENS_REFRESH_ALLOWED=true
      - STASIS_IDENTITY_UI_DEV_CLIENT_ID=a928359a-e2ee-4db7-9307-8071b2a1c756
      - STASIS_IDENTITY_UI_DEV_REDIRECT_URI=https://localhost:8080/manage/login/callback
      - STASIS_IDENTITY_UI_DEV_CLIENT_SECRET=test-secret
      - STASIS_IDENTITY_UI_DEV_OWNER_PASSWORD=passw0rd
    volumes:
      - ./bootstrap.conf:/opt/docker/config/bootstrap.conf
      - ./certs/localhost.p12:/opt/docker/certs/localhost.p12

  identity-ui:
    image: stasis-identity-ui:dev-latest
    command: /bin/sh -c "yarn serve"
    ports:
      - '8080:8080'
    environment:
      - VUE_APP_STASIS_IDENTITY_UI_API_URL=https://localhost:8080/api
      - VUE_APP_STASIS_IDENTITY_UI_AUTH_CLIENT_ID=a928359a-e2ee-4db7-9307-8071b2a1c756
      - VUE_APP_STASIS_IDENTITY_UI_AUTH_REDIRECT_URI=https://localhost:8080/manage/login/callback
    volumes:
      - '../:/opt/stasis-identity-ui'
