{
 "title": "Overview",
 "tags": [ "db" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "db",
    "label": "Database",
    "query": {
     "query": "pg_stat_activity_count{datname!~\"template.*\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=~\"db-.*\"}[1m]) * 60) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(process_resident_memory_bytes{job=~\"db-.*\"}[$__rate_interval])) by (job)",
     "legendFormat": "Residen [{{job}}]"
    },
    {
     "expr": "sum(rate(process_virtual_memory_bytes{job=~\"db-.*\"}[$__rate_interval])) by (job)",
     "legendFormat": "Virtual [{{job}}]"
    }
   ]
  },
  {
   "title": "Open Files",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{job=~\"db-.*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "pg_stat_database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Active Time",
   "type": "timeseries",
   "description": "Time spent executing SQL statements in this database, in milliseconds",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_active_time{datname=~\"$db\"}[$__rate_interval])) by (datname,job) != 0",
     "legendFormat": "[{{job}}] - {{datname}}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_database_blks_hit{datname=~\"$db\",datid!=\"0\"} / (pg_stat_database_blks_read{datname=~\"$db\",datid!=\"0\"} + pg_stat_database_blks_hit{datname=~\"$db\",datid!=\"0\"})",
     "legendFormat": "[{{job}}] - {{datname}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "description": "Number of transactions in this database that have been committed or rolled back",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_xact_commit{datname=~\"$db\",datid!=\"0\"}[$__rate_interval])) by (datname, job)",
     "legendFormat": "Committed [{{job}}] {{datname}}"
    },
    {
     "expr": "sum(rate(pg_stat_database_xact_rollback{datname=~\"$db\",datid!=\"0\"}[$__rate_interval])) by (datname, job)",
     "legendFormat": "Rolled back [{{job}}] {{datname}}"
    }
   ]
  },
  {
   "title": "Rows",
   "type": "timeseries",
   "description": "Number of rows returned, fetched, inserted, updated or deleted by queries in this database",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_tup_returned{datname=~\"$db\",datid!=\"0\"}[$__rate_interval])) by (datname,job)",
     "legendFormat": "Returned [{{job}}] {{datname}}"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_fetched{datname=~\"$db\",datid!=\"0\"}[$__rate_interval])) by (datname,job)",
     "legendFormat": "Fetched [{{job}}] {{datname}}"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_inserted{datname=~\"$db\",datid!=\"0\"}[$__rate_interval])) by (datname,job)",
     "legendFormat": "Inserted [{{job}}] {{datname}}"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_updated{datname=~\"$db\",datid!=\"0\"}[$__rate_interval])) by (datname,job)",
     "legendFormat": "Updated [{{job}}] {{datname}}"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_deleted{datname=~\"$db\",datid!=\"0\"}[$__rate_interval])) by (datname,job)",
     "legendFormat": "Deleted [{{job}}] {{datname}}"
    }
   ]
  },
  {
   "title": "Transaction Idle Time",
   "type": "timeseries",
   "description": "Time spent idling while in a transaction in this database, in milliseconds (this corresponds to the states idle in transaction and idle in transaction (aborted) in pg_stat_activity)",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_idle_in_transaction_time{datname=~\"$db\",datid!=\"0\"}[$__rate_interval])) by (datname,job)",
     "legendFormat": "[{{job}}] {{datname}}"
    }
   ]
  },
  {
   "title": "Connected Backends",
   "type": "stat",
   "description": "Number of backends currently connected to this database",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_numbackends{datname=~\"$db\",datid!=\"0\"}) by (datname,job)",
     "legendFormat": "[{{job}}] {{datname}}"
    }
   ]
  },
  {
   "title": "Deadlocks",
   "type": "stat",
   "description": "Number of deadlocks detected in this database",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_deadlocks{datname=~\"$db\",datid!=\"0\"}) by (datname,job)",
     "legendFormat": "[{{job}}] {{datname}}"
    }
   ]
  },
  {
   "title": "Terminated Sessions",
   "type": "timeseries",
   "description": "Number of database sessions to this database that were terminated because connection to the client was lost (abandoned), because of fatal errors (fatal) or due to operator intervention (killed)",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(pg_stat_database_sessions_abandoned{datname=~\"$db\",datid!=\"0\"}) by (datname,job)",
     "legendFormat": "Abandoned [{{job}}] {{datname}}"
    },
    {
     "expr": "sum(pg_stat_database_sessions_fatal{datname=~\"$db\",datid!=\"0\"}) by (datname,job)",
     "legendFormat": "Fatal [{{job}}] {{datname}}"
    },
    {
     "expr": "sum(pg_stat_database_sessions_killed{datname=~\"$db\",datid!=\"0\"}) by (datname,job)",
     "legendFormat": "Killed [{{job}}] {{datname}}"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "stat",
   "description": "Total number of sessions established to this database",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_sessions{datname=~\"$db\",datid!=\"0\"}) by (datname,job)",
     "legendFormat": "[{{job}}] {{datname}}"
    }
   ]
  },
  { "title": "pg_stat_activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{datname=~\"$db\"}) by (datname,state)",
     "legendFormat": "[{{datname}}] - {{state}}"
    }
   ]
  },
  { "title": "pg_stat_bgwriter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Buffers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_bgwriter_buffers_clean[$__rate_interval])) by (job)",
     "legendFormat": "Clean [{{job}}]"
    },
    {
     "expr": "sum(rate(pg_stat_bgwriter_buffers_backend[$__rate_interval])) by (job)",
     "legendFormat": "Backend [{{job}}]"
    },
    {
     "expr": "sum(rate(pg_stat_bgwriter_buffers_checkpoint[$__rate_interval])) by (job)",
     "legendFormat": "Checkpoint [{{job}}]"
    },
    {
     "expr": "sum(rate(pg_stat_bgwriter_buffers_alloc[$__rate_interval])) by (job)",
     "legendFormat": "Allocated [{{job}}]"
    }
   ]
  },
  {
   "title": "Backend / fsync",
   "type": "stat",
   "description": "Number of times a backend had to execute its own fsync call (normally the background writer handles those even when the backend does its own write)",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_bgwriter_buffers_backend_fsync) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Clean / Max Written",
   "type": "stat",
   "description": "Number of times the background writer stopped a cleaning scan because it had written too many buffers",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_bgwriter_maxwritten_clean) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Checkpoint / Time",
   "type": "timeseries",
   "description": "Amount of time that has been spent in the portion of checkpoint processing where files are written and synchronized to disk, in milliseconds",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_bgwriter_checkpoint_write_time[$__rate_interval])) by (job)",
     "legendFormat": "[{{job}}] Write"
    },
    {
     "expr": "sum(rate(pg_stat_bgwriter_checkpoint_sync_time[$__rate_interval])) by (job)",
     "legendFormat": "[{{job}}] Sync"
    }
   ]
  },
  {
   "title": "Checkpoint / Total Time",
   "type": "stat",
   "description": "Total amount of time that has been spent in the portion of checkpoint processing where files are written and synchronized to disk, in milliseconds",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_bgwriter_checkpoint_write_time) by (job)",
     "legendFormat": "[{{job}}] Write"
    },
    {
     "expr": "sum(pg_stat_bgwriter_checkpoint_sync_time) by (job)",
     "legendFormat": "[{{job}}] Sync"
    }
   ]
  },
  {
   "title": "Checkpoints",
   "type": "bargauge",
   "description": "Number of scheduled (timed) and requested checkpoints that have been performed",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_bgwriter_checkpoints_req) by (job)",
     "legendFormat": "[{{job}}] Requested"
    },
    {
     "expr": "sum(pg_stat_bgwriter_checkpoints_timed) by (job)",
     "legendFormat": "[{{job}}] Timed"
    }
   ]
  }
 ]
}