{
 "title": "Key-Value Stores",
 "tags": [ "server" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "backend",
    "label": "Backend",
    "query": {
     "query": "stasis_server_persistence_kv_put_operations_total"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Put",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(stasis_server_persistence_kv_put_operations_total{backend=~\"$backend\"}[$__rate_interval])) by (backend)",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "Get",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(stasis_server_persistence_kv_get_operations_total{backend=~\"$backend\"}[$__rate_interval])) by (backend)",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "Delete",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(stasis_server_persistence_kv_delete_operations_total{backend=~\"$backend\"}[$__rate_interval])) by (backend)",
     "legendFormat": "{{backend}}"
    }
   ]
  }
 ]
}