{
 "title": "I/O",
 "tags": [ "server" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Declared",
   "type": "timeseries",
   "description": "Amount of data declared via reservations and manifests",
   "gridPos": { "h": 11, "w": 19, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(stasis_server_persistence_reservation_store_reservation_bytes_total[$__rate_interval]))",
     "legendFormat": "Reservations"
    },
    {
     "expr": "sum(rate(stasis_server_persistence_manifest_store_manifest_bytes_total[$__rate_interval]))",
     "legendFormat": "Manifests"
    }
   ]
  },
  {
   "title": "Declared / Interval",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(stasis_server_persistence_reservation_store_reservation_bytes_total[$__range]))",
     "legendFormat": "Reservations"
    },
    {
     "expr": "sum(increase(stasis_server_persistence_manifest_store_manifest_bytes_total[$__range]))",
     "legendFormat": "Manifests"
    }
   ]
  },
  {
   "title": "Routed",
   "type": "timeseries",
   "description": "Amount of data routed",
   "gridPos": { "h": 11, "w": 19, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(stasis_server_routers_push_bytes_total[$__rate_interval]))",
     "legendFormat": "Pushed"
    },
    {
     "expr": "sum(rate(stasis_server_routers_pull_bytes_total[$__rate_interval]))",
     "legendFormat": "Pulled"
    },
    {
     "expr": "sum(rate(stasis_server_routers_discard_bytes_total[$__rate_interval]))",
     "legendFormat": "Discarded"
    },
    {
     "expr": "sum(rate(stasis_server_routers_reserve_bytes_total[$__rate_interval]))",
     "legendFormat": "Reserved"
    },
    {
     "expr": "sum(rate(stasis_server_routers_stage_bytes_total[$__rate_interval]))",
     "legendFormat": "Staged"
    }
   ]
  },
  {
   "title": "Routed / Interval",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 5, "x": 19, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(stasis_server_routers_push_bytes_total[$__range]))",
     "legendFormat": "Pushed"
    },
    {
     "expr": "sum(increase(stasis_server_routers_pull_bytes_total[$__range]))",
     "legendFormat": "Pulled"
    },
    {
     "expr": "sum(increase(stasis_server_routers_discard_bytes_total[$__range]))",
     "legendFormat": "Discarded"
    },
    {
     "expr": "sum(increase(stasis_server_routers_reserve_bytes_total[$__range]))",
     "legendFormat": "Reserved"
    },
    {
     "expr": "sum(increase(stasis_server_routers_stage_bytes_total[$__range]))",
     "legendFormat": "Staged"
    }
   ]
  },
  {
   "title": "Persisted",
   "type": "timeseries",
   "description": "Amount of persisted/streamed data",
   "gridPos": { "h": 11, "w": 19, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(stasis_server_persistence_streaming_write_bytes_total[$__rate_interval]))",
     "legendFormat": "Written"
    },
    {
     "expr": "sum(rate(stasis_server_persistence_streaming_read_bytes_total[$__rate_interval]))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Persisted / Interval",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 5, "x": 19, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(stasis_server_persistence_streaming_write_bytes_total[$__range]))",
     "legendFormat": "Written"
    },
    {
     "expr": "sum(increase(stasis_server_persistence_streaming_read_bytes_total[$__range]))",
     "legendFormat": "Read"
    }
   ]
  }
 ]
}