{
 "title": "Overview",
 "tags": [ "server" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Persistence / Streaming Stores", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(stasis_server_persistence_streaming_write_bytes_total[$__rate_interval])) by (backend)",
     "legendFormat": "[{{backend}}] - Write"
    },
    {
     "expr": "sum(rate(stasis_server_persistence_streaming_read_bytes_total[$__rate_interval])) by (backend)",
     "legendFormat": "[{{backend}}] - Read"
    }
   ]
  },
  {
   "title": "Data / Interval",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(stasis_server_persistence_streaming_write_bytes_total[$__range]))",
     "legendFormat": "Written"
    },
    {
     "expr": "sum(increase(stasis_server_persistence_streaming_read_bytes_total[$__range]))",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(stasis_server_persistence_streaming_write_operations_total[$__rate_interval])) by (backend)",
     "legendFormat": "[{{backend}}] - Write"
    },
    {
     "expr": "sum(rate(stasis_server_persistence_streaming_read_operations_total[$__rate_interval])) by (backend)",
     "legendFormat": "[{{backend}}] - Read"
    },
    {
     "expr": "sum(rate(stasis_server_persistence_streaming_discard_operations_total[$__rate_interval])) by (backend)",
     "legendFormat": "[{{backend}}] - Discard"
    },
    {
     "expr": "sum(rate(stasis_server_persistence_streaming_init_operations_total[$__rate_interval])) by (backend)",
     "legendFormat": "[{{backend}}] - Init"
    },
    {
     "expr": "sum(rate(stasis_server_persistence_streaming_drop_operations_total[$__rate_interval])) by (backend)",
     "legendFormat": "[{{backend}}] - Drop"
    }
   ]
  },
  {
   "title": "Data / Total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(stasis_server_persistence_streaming_write_bytes_total)",
     "legendFormat": "Written"
    },
    {
     "expr": "sum(stasis_server_persistence_streaming_read_bytes_total)",
     "legendFormat": "Read"
    }
   ]
  },
  { "title": "Persistence / Key-Value Stores", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Operations",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(stasis_server_persistence_store_put_operations_total[$__rate_interval])) by (backend)",
     "legendFormat": "[{{backend}}] - Put"
    },
    {
     "expr": "sum(rate(stasis_server_persistence_store_get_operations_total[$__rate_interval])) by (backend)",
     "legendFormat": "[{{backend}}] - Get"
    },
    {
     "expr": "sum(rate(stasis_server_persistence_store_delete_operations_total[$__rate_interval])) by (backend)",
     "legendFormat": "[{{backend}}] - Delete"
    }
   ]
  },
  { "title": "Persistence / Other Stores", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Manifests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(stasis_server_persistence_manifest_store_manifests_total[$__rate_interval]))",
     "legendFormat": "Manifests"
    }
   ]
  },
  {
   "title": "Manifest Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(stasis_server_persistence_manifest_store_manifest_bytes_total[$__rate_interval]))",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Reservations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(stasis_server_persistence_reservation_store_reservations_total[$__rate_interval])) by (target)",
     "legendFormat": "Target [{{target}}]"
    }
   ]
  },
  {
   "title": "Reservation Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(stasis_server_persistence_reservation_store_reservation_bytes_total[$__rate_interval])) by (target)",
     "legendFormat": "Target [{{target}}]"
    }
   ]
  },
  {
   "title": "Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(stasis_server_persistence_event_log_events_total[$__rate_interval])) by (backend)",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  { "title": "Routing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(stasis_server_routers_push_bytes_total[$__rate_interval])) by (router)",
     "legendFormat": "[{{router}}] - Push"
    },
    {
     "expr": "sum(rate(stasis_server_routers_pull_bytes_total[$__rate_interval])) by (router)",
     "legendFormat": "[{{router}}] - Pull"
    },
    {
     "expr": "sum(rate(stasis_server_routers_discard_bytes_total[$__rate_interval])) by (router)",
     "legendFormat": "[{{router}}] - Discard"
    },
    {
     "expr": "sum(rate(stasis_server_routers_reserve_bytes_total[$__rate_interval])) by (router)",
     "legendFormat": "[{{router}}] - Reserve"
    },
    {
     "expr": "sum(rate(stasis_server_routers_stage_bytes_total[$__rate_interval])) by (router)",
     "legendFormat": "[{{router}}] - Stage"
    }
   ]
  },
  {
   "title": "Push",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(stasis_server_routers_push_operations_total[$__rate_interval])) by (router)",
     "legendFormat": "Successful - [{{router}}]"
    },
    {
     "expr": "sum(rate(stasis_server_routers_push_operation_failures_total[$__rate_interval])) by (router,reason)",
     "legendFormat": "Failed - [{{router}}] / [{{reason}}]"
    }
   ]
  },
  {
   "title": "Pull",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(stasis_server_routers_pull_operations_total[$__rate_interval])) by (router)",
     "legendFormat": "Successful - [{{router}}]"
    },
    {
     "expr": "sum(rate(stasis_server_routers_pull_operation_failures_total[$__rate_interval])) by (router,reason)",
     "legendFormat": "Failed - [{{router}}] / [{{reason}}]"
    }
   ]
  },
  {
   "title": "Discard",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(stasis_server_routers_discard_operations_total[$__rate_interval])) by (router)",
     "legendFormat": "Successful - [{{router}}]"
    },
    {
     "expr": "sum(rate(stasis_server_routers_discard_operation_failures_total[$__rate_interval])) by (router,reason)",
     "legendFormat": "Failed - [{{router}}] / [{{reason}}]"
    }
   ]
  },
  {
   "title": "Reserve",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(stasis_server_routers_reserve_operations_total[$__rate_interval])) by (router)",
     "legendFormat": "Successful - [{{router}}]"
    },
    {
     "expr": "sum(rate(stasis_server_routers_reserve_operation_failures_total[$__rate_interval])) by (router,reason)",
     "legendFormat": "Failed - [{{router}}] / [{{reason}}]"
    }
   ]
  },
  {
   "title": "Stage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(stasis_server_routers_stage_operations_total[$__rate_interval])) by (router)",
     "legendFormat": "Successful - [{{router}}]"
    }
   ]
  },
  { "title": "APIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(stasis_server_endpoints_requests_total[$__rate_interval])) by (endpoint, method)",
     "legendFormat": "[{{method}}] - {{endpoint}}"
    }
   ]
  },
  {
   "title": "Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(stasis_server_endpoints_response_times_count[$__rate_interval])) by (endpoint, method, status)",
     "legendFormat": "[{{method}}] - [{{status}}] - {{endpoint}}"
    },
    {}
   ]
  },
  {
   "title": "Response Times",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "targets": [
    {
     "expr": "sum(rate(stasis_server_endpoints_response_times_bucket[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Security", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 } },
  {
   "title": "Authenticators",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(stasis_server_authenticators_authentication_successful_total[$__rate_interval])) by (authenticator)",
     "legendFormat": "{{authenticator}}"
    },
    {
     "expr": "sum(rate(stasis_server_authenticators_authentication_failed_total[$__rate_interval])) by (authenticator)",
     "legendFormat": "{{authenticator}}"
    }
   ]
  },
  {
   "title": "Key Providers",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(stasis_server_key_providers_key_refresh_successful_total[$__rate_interval])) by (provider)",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "OAuth Client Tokens",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(stasis_server_oauth_clients_tokens_total[$__rate_interval])) by (endpoint,grant_type)",
     "legendFormat": "{{endpoint}} - [{{grant_type}}]"
    }
   ]
  }
 ]
}