name: Stasis Builds

on: [push, pull_request]

jobs:
  scala:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt

      - name: Run QA
        run: |
          mkdir ${{ github.workspace }}/target
          sbt qa

      - name: Publish Artifacts
        run: |
          sbt "project client" universal:packageBin

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: stasis-client-${{ github.sha }}
          path: client/target/universal/stasis-client-*.zip
          if-no-files-found: error
          retention-days: 1

      - name: Push Coverage Result
        uses: codecov/codecov-action@v3
        with:
          flags: scala

  python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Run QA
        run: |
          cd client-cli
          pip install -e .
          pip install coverage pylint
          ./qa.py
          python -m coverage xml

      - name: Publish Artifacts
        run: |
          cd client-cli
          python setup.py bdist --format=zip

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: stasis-client-cli-${{ github.sha }}
          path: client-cli/dist/stasis-client-cli-*.zip
          if-no-files-found: error
          retention-days: 1

      - name: Push Coverage Result
        uses: codecov/codecov-action@v3
        with:
          flags: python

  flutter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Run identity QA
        run: |
          sudo apt install -y lcov
          cd identity-ui
          ./qa.py
      - name: Run server QA
        run: |
          sudo apt install -y lcov
          cd server-ui
          ./qa.py

  android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt

      - name: Run QA
        run: |
          cd client-android
          ./gradlew qa
