name: Stasis Release

on:
  workflow_dispatch:
    inputs:
      next_version:
        description: 'Next release version'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
      verbose:
        description: 'Enable debug logging during release'
        required: false
        type: boolean

jobs:
  release:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v4
        with:
          ref: master

      - name: Setup Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Release project
        run: |
          pip install semver
          git config --global user.name ${{github.actor}}
          git config --global user.email ${{github.actor}}@users.noreply.github.com
          ./release.py $VERBOSE --next $NEXT_VERSION
          git push

        env:
          NEXT_VERSION: ${{ inputs.next_version }}
          VERBOSE: ${{ inputs.verbose && '--verbose' || '' }}
